/**
 * The whole game's card catalog, counted from the committed MarvelCDB cache (`raw/marvelcdb/*.json`), for the Title
 * footer's "N / M cards live": M is every card in the game, not just the packs this app has ingested.
 *
 *   pnpm --filter @mc/content catalog
 *
 * One catalog card is one printed card, however the app models it:
 * - a double-sided card (an identity, a two-sided main scheme, a villain's own stages) counts once — MarvelCDB lists
 *   the faces as `01001a`/`01001b`, and those collapse to `01001` (`printedCodeOf`, `src/data/catalog-codes.ts`);
 * - a reprint (a card MarvelCDB marks `duplicate_of_code`, e.g. a precon's copy of a Core card) isn't a new card, so
 *   it isn't counted; `CATALOG_REPRINTS` maps it to the original so the app's own reprint ids still resolve.
 *
 * Writes `src/data/catalog.ts`. `src/data/catalog.test.ts` fails if that file drifts from the cache, so re-run this
 * after an ingest adds or refreshes a pack. Runs under Node type stripping, like `ingest-marvelcdb.ts`.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { catalogOf, type RawCatalogPack } from "../src/data/catalog-codes.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rawDir = join(root, "raw", "marvelcdb");

const files = (await readdir(rawDir)).filter((name) => name.endsWith(".json")).sort();
const packs: RawCatalogPack[] = [];
for (const file of files) packs.push(JSON.parse(await readFile(join(rawDir, file), "utf8")) as RawCatalogPack);
const catalog = catalogOf(packs);

const reprints = Object.entries(catalog.reprints)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([code, original]) => `  "${code}": "${original}",`)
  .join("\n");

const source = `// Generated by scripts/generate-catalog.ts from raw/marvelcdb/*.json. Do not hand-edit: re-run
// \`pnpm --filter @mc/content catalog\` after an ingest adds or refreshes a pack.

/** How many MarvelCDB packs the catalog was counted from. */
export const CATALOG_PACK_COUNT = ${catalog.packCount};

/** Every printed card in the game: one per card, double-sided cards once, reprints not counted again. */
export const CATALOG_CARD_COUNT = ${catalog.cardCount};

/** A reprint's printed code → the original card it reprints. */
export const CATALOG_REPRINTS: Readonly<Record<string, string>> = {
${reprints}
};
`;

await writeFile(join(root, "src", "data", "catalog.ts"), source);
console.log(
  `catalog: ${catalog.cardCount} cards from ${catalog.packCount} packs, ${Object.keys(catalog.reprints).length} reprints`,
);
