/**
 * docs/phase7-wave8.md §3.42: "Attached ally … is considered to have a wild ([wild]) resource icon in addition to its
 * printed resource icon" is `RuleSpec consideredResourceIcon { target, resource }`, read through
 * `rules.ts` `resourceIconsInPlay`.
 *
 * RRG 1.8 "Printed" (p. 34): a considered icon is not a printed one, so the printed icons are untouched. "Resource"
 * (p. 37): resources are generated by a card discarded from a hand or by a resource ability, and the card the rule
 * names is in play, so nothing it could pay with changes. In a closed in-play scenario area the rule applies only when
 * its ability reaches the area (§3.33, §4.1 Q19 = B). The pairing that reads the icon is §3.36
 * (`pair-cards.test.ts`). Synthetic cards only.
 */

import { flat, type CardId } from "@mc/content";
import { describe, expect, it } from "vitest";
import type { EngineDeps, RuleSpec } from "./abilities.js";
import { handCardResources } from "./actions.js";
import { startSession } from "./engine.js";
import type { InstanceId } from "./ids.js";
import { showingResources } from "./query.js";
import { resourceIconsInPlay } from "./rules.js";
import type { EffectSpec, Predicate, TargetRef } from "./spec.js";
import type { GameState } from "./state.js";
import { depsOf, stubAbility } from "./testing/abilities.js";
import { driveSession } from "./testing/drive.js";
import {
  stubAlly,
  stubEvent,
  stubMainScheme,
  stubSideScheme,
  stubTreachery,
  stubUpgrade,
  stubVillain,
} from "./testing/fixtures.js";
import { giveCard } from "./testing/scenario.js";
import { copiesOf, gameAtFirstTurn, P1, playerCardIntoPlay } from "./testing/wave3.js";

const AREA = "mission";
const INTO = { scenarioPlayArea: AREA } as const;
const THERE = { inScenarioPlayArea: AREA } as const;
const you = { kind: "controller" } as const;
const HOST = { categories: ["ally"], hostOfSelf: true } as const;
const find = (name: string): TargetRef => ({ kind: "find", query: { name } });
const NONE = { physical: 0, mental: 0, energy: 0, wild: 0 };

/** "Attach to an ally. Attached ally is considered to have a [wild] resource icon in addition to its printed one." */
const PLAIN_RULE = stubAbility("sash.constant", {
  trigger: { kind: "constant", rules: [{ kind: "consideredResourceIcon", target: HOST, resource: "wild" }] },
  effects: [],
});
/** The same text on a card whose ability refers to the area. */
const REACHING_RULE = stubAbility("orders.constant", {
  trigger: { kind: "constant", rules: [{ kind: "consideredResourceIcon", target: HOST, resource: "wild" }] },
  reaches: INTO,
  effects: [],
});
/** "Attached ally is considered to have a [mental] resource icon …" */
const MENTAL_RULE = stubAbility("lens.constant", {
  trigger: { kind: "constant", rules: [{ kind: "consideredResourceIcon", target: HOST, resource: "mental" }] },
  effects: [],
});
const upgrade = (id: string, ref: (typeof PLAIN_RULE)["ref"]) => ({
  ...stubUpgrade({ id, cost: 0, abilities: [ref] }),
  attachesTo: { kind: "ally" as const },
});
const SASH = upgrade("sash", PLAIN_RULE.ref);
const ORDERS = upgrade("orders", REACHING_RULE.ref);
const LENS = upgrade("lens", MENTAL_RULE.ref);
const SCOUT = stubAlly({ id: "scout", cost: 0, atk: 2, thw: 1, hp: 2, resourceIcons: { energy: 1 } });

const ERRAND = stubSideScheme({ id: "errand", startingThreat: 5, boostIcons: 0 });
const schemeThere: Predicate = { kind: "exists", query: { categories: ["sideScheme"], ...THERE } };
const RULES: readonly RuleSpec[] = [
  {
    kind: "playDestination",
    cards: { categories: ["ally"] },
    area: AREA,
    attachments: { categories: ["upgrade"] },
    while: schemeThere,
  },
];
const action = (id: string, ...effects: EffectSpec[]) => {
  const ability = stubAbility(`${id}.action`, { trigger: { kind: "action" }, effects });
  return { card: stubEvent({ id, cost: 0, abilities: [ability.ref] }), ability };
};
const OPEN = action(
  "open",
  { kind: "createScenarioPlayArea", name: AREA, closed: true },
  { kind: "putIntoPlay", card: find(ERRAND.name), controller: you, into: INTO },
);

const SCHEME = stubMainScheme({
  id: "long",
  stages: [{ startingThreat: flat(0), targetThreat: flat(99), acceleration: flat(0) }],
});
const TYRANT = stubVillain({ id: "tyrant", stages: [{ hp: flat(40), atk: 0, sch: 0 }] });
const NOISE = stubTreachery({ id: "noise", boostIcons: 0 });
const deps: EngineDeps = depsOf(PLAIN_RULE, REACHING_RULE, MENTAL_RULE, OPEN.ability);

function start(): GameState {
  const base = gameAtFirstTurn({
    cards: [ERRAND, SCOUT, SASH, ORDERS, LENS, NOISE, OPEN.card],
    deps,
    villain: TYRANT,
    mainScheme: SCHEME,
    encounter: [ERRAND.id, ...copiesOf(NOISE.id, 14)],
    deck: [SCOUT.id, SCOUT.id, SASH.id, SASH.id, ORDERS.id, LENS.id, OPEN.card.id],
    scenarioRuleSpecs: RULES,
  });
  const given = giveCard(base, P1, OPEN.card.id);
  return driveSession(startSession(given.state), deps, [
    { type: "playCard", playerId: P1, cardInstanceId: given.id, payment: [], attachToInstanceId: null },
  ]).session.state;
}
/** Plays `card` (cost 0) from P1's hand, onto `host` or into the area. */
function play(state: GameState, card: CardId, opts: { host?: InstanceId; into?: boolean } = {}) {
  const given = giveCard(state, P1, card);
  const run = driveSession(startSession(given.state), deps, [
    {
      type: "playCard",
      playerId: P1,
      cardInstanceId: given.id,
      payment: [],
      attachToInstanceId: opts.host ?? null,
      ...(opts.into ? { into: INTO } : {}),
    },
  ]);
  return { state: run.session.state, id: given.id };
}

describe("§3.42 a resource icon a card in play is considered to have", () => {
  it("an ally with a printed [energy] icon and the upgrade has [energy] and [wild]; its printed icons are unchanged, and without the upgrade it has only [energy]", () => {
    const ally = playerCardIntoPlay(start(), SCOUT.id);
    expect(resourceIconsInPlay(ally.state, deps, ally.id)).toEqual({
      icons: { ...NONE, energy: 1 },
      considered: NONE,
    });
    const run = play(ally.state, SASH.id, { host: ally.id });
    expect(resourceIconsInPlay(run.state, deps, ally.id)).toEqual({
      icons: { ...NONE, energy: 1, wild: 1 },
      considered: { ...NONE, wild: 1 },
    });
    expect(showingResources(run.state, ally.id)).toEqual({ ...NONE, energy: 1 });
    // Only the attached ally: the upgrade itself and another copy of the ally are as printed.
    expect(resourceIconsInPlay(run.state, deps, run.id).considered).toEqual(NONE);
    const other = playerCardIntoPlay(run.state, SCOUT.id);
    expect(resourceIconsInPlay(other.state, deps, other.id).considered).toEqual(NONE);
  });

  it("each rule in force adds one icon: two upgrades of different kinds add a [wild] and a [mental]", () => {
    const ally = playerCardIntoPlay(start(), SCOUT.id);
    const one = play(ally.state, SASH.id, { host: ally.id });
    const two = play(one.state, LENS.id, { host: ally.id });
    expect(resourceIconsInPlay(two.state, deps, ally.id).icons).toEqual({ ...NONE, energy: 1, wild: 1, mental: 1 });
  });

  it("pays for nothing: a copy of the ally in hand still generates its one printed [energy]", () => {
    const ally = playerCardIntoPlay(start(), SCOUT.id);
    const run = play(ally.state, SASH.id, { host: ally.id });
    const inHand = giveCard(run.state, P1, SCOUT.id);
    expect(handCardResources(inHand.state, deps, inHand.id, P1, null)).toEqual({ ...NONE, energy: 1 });
  });

  it("the icon leaves with the upgrade", () => {
    const ally = playerCardIntoPlay(start(), SCOUT.id);
    const run = play(ally.state, SASH.id, { host: ally.id });
    const without: GameState = {
      ...run.state,
      instances: {
        ...run.state.instances,
        [ally.id]: { ...run.state.instances[ally.id]!, attachments: [] },
        [run.id]: { ...run.state.instances[run.id]!, attachedTo: null },
      },
    };
    expect(resourceIconsInPlay(without, deps, ally.id).considered).toEqual(NONE);
  });

  it("Q19 = B: on an ally in a closed area an ordinary upgrade's rule does not apply; one whose ability reaches the area does", () => {
    const ally = play(start(), SCOUT.id, { into: true });
    const plain = play(ally.state, SASH.id, { host: ally.id });
    expect(plain.state.instances[plain.id]?.attachedTo).toBe(ally.id);
    expect(resourceIconsInPlay(plain.state, deps, ally.id)).toEqual({
      icons: { ...NONE, energy: 1 },
      considered: NONE,
    });
    const reaching = play(plain.state, ORDERS.id, { host: ally.id });
    expect(resourceIconsInPlay(reaching.state, deps, ally.id)).toEqual({
      icons: { ...NONE, energy: 1, wild: 1 },
      considered: { ...NONE, wild: 1 },
    });
  });
});
