/**
 * docs/phase7-wave5.md §3.16: how a card was paid for, resources by source. Synthetic cards shaped like SP//dr Suit's
 * "Sync Ratio" resource ability (`spdr` 31001b) and VEN#m / Rapid Deployment ("for each resource generated by SP//dr
 * Suit's 'Sync Ratio' ability to pay for her", "If you paid for this card using a resource generated by … 'Sync
 * Ratio'").
 */

import { describe, expect, it } from "vitest";
import type { EngineDeps } from "./abilities.js";
import { replay, startSession } from "./engine.js";
import type { InstanceId } from "./ids.js";
import { mustInstance } from "./query.js";
import type { GameState } from "./state.js";
import { depsOf, stubAbility } from "./testing/abilities.js";
import { driveSession } from "./testing/drive.js";
import { stubEvent, stubSupport } from "./testing/fixtures.js";
import { giveCard, RESOURCE } from "./testing/scenario.js";
import { copiesOf, gameAtFirstTurn, P1, playerCardIntoPlay } from "./testing/wave3.js";

const SYNC_RATIO = stubAbility("suit.sync-ratio", { trigger: { kind: "resource" }, generates: 2, effects: [] });
const SUIT = stubSupport({ id: "suit", cost: 0, abilities: [SYNC_RATIO.ref] });

const VENOM_ACTION = stubAbility("venom-shot.action", {
  trigger: { kind: "action" },
  effects: [
    {
      kind: "dealDamage",
      target: { kind: "villain" },
      amount: { kind: "var", name: `paid.ability.${SYNC_RATIO.ref.id}` },
    },
  ],
});
const VENOM_SHOT = stubEvent({ id: "venom-shot", cost: 3, abilities: [VENOM_ACTION.ref] });

const deps: EngineDeps = depsOf(SYNC_RATIO, VENOM_ACTION);

function start(): { readonly state: GameState; readonly suit: InstanceId } {
  const state = gameAtFirstTurn({
    cards: [SUIT, VENOM_SHOT],
    deps,
    deck: [SUIT.id, VENOM_SHOT.id, ...copiesOf(RESOURCE.id, 3)],
  });
  const placed = playerCardIntoPlay(state, SUIT.id);
  return { state: placed.state, suit: placed.id };
}

const villainDamage = (state: GameState) => mustInstance(state, state.villains[0]!.instanceId).damage;

describe("§3.16 resources paid, by the ability that generated them", () => {
  it("counts the resources Sync Ratio generated toward the card; replay deep-equal", () => {
    const { state, suit } = start();
    const shot = giveCard(state, P1, VENOM_SHOT.id);
    const res = giveCard(shot.state, P1, RESOURCE.id);
    const { session } = driveSession(startSession(res.state), deps, [
      {
        type: "playCard",
        playerId: P1,
        cardInstanceId: shot.id,
        payment: [{ ability: { instanceId: suit, abilityId: SYNC_RATIO.ref.id } }, { fromHand: res.id }],
        attachToInstanceId: null,
      },
    ]);
    expect(villainDamage(session.state)).toBe(villainDamage(state) + 2);
    const replayed = replay(session.log, deps);
    if (!replayed.ok) throw new Error(replayed.error.message);
    expect(replayed.state).toEqual(session.state);
  });

  it("is 0 when the card was paid for another way", () => {
    const { state } = start();
    const shot = giveCard(state, P1, VENOM_SHOT.id);
    const seat = shot.state.players[0]!;
    const ids = [...seat.hand, ...seat.deck]
      .filter((id) => mustInstance(shot.state, id).cardId === RESOURCE.id)
      .slice(0, 3);
    // Test surgery: those three resource cards in hand.
    const s: GameState = {
      ...shot.state,
      players: shot.state.players.map((p, i) =>
        i === 0 ? { ...p, hand: [...new Set([...p.hand, ...ids])], deck: p.deck.filter((id) => !ids.includes(id)) } : p,
      ),
    };
    const { session } = driveSession(startSession(s), deps, [
      {
        type: "playCard",
        playerId: P1,
        cardInstanceId: shot.id,
        payment: ids.map((id) => ({ fromHand: id })),
        attachToInstanceId: null,
      },
    ]);
    expect(villainDamage(session.state)).toBe(villainDamage(state));
  });
});
