/**
 * docs/phase7-wave4.md §3.38: resources generated by reading the table. Synthetic cards shaped like Energy
 * Duplication (`mts` 21006: "generate the printed resource on your faceup energy form upgrade") and Band Together
 * (`mts` 21018: "This card generates [wild] for each ally you control (to a maximum of 3)").
 *
 * Sources: the cards' own text; RRG 1.8 "Resources" (p. 37), "Printed" (p. 35).
 */

import { describe, expect, it } from "vitest";
import type { EngineDeps } from "./abilities.js";
import { generatedResources, handCardResources } from "./actions.js";
import type { InstanceId } from "./ids.js";
import type { GameState } from "./state.js";
import { depsOf, stubAbility } from "./testing/abilities.js";
import { stubAlly, stubResource, stubSupport, stubUpgrade } from "./testing/fixtures.js";
import { giveCard } from "./testing/scenario.js";
import { copiesOf, gameAtFirstTurn, P1, playerCardIntoPlay } from "./testing/wave3.js";

const PHOTON = {
  ...stubUpgrade({ id: "photon", cost: 0 }),
  resourceIcons: { energy: 0, mental: 1, physical: 0, wild: 0 },
};
const BAND = stubAbility("band.constant", {
  trigger: {
    kind: "constant",
    handGenerates: { kind: "perCard", resource: "wild", per: { categories: ["ally"], controller: "you" }, max: 3 },
  },
  effects: [],
});
const BAND_CARD = stubResource({ id: "band", icons: 0, abilities: [BAND.ref] });
const ALLY = stubAlly({ id: "pal", cost: 0, atk: 1, thw: 1, hp: 2 });
const DUP = stubSupport({ id: "dup", cost: 0 });
const deps: EngineDeps = depsOf(BAND);

function start(allies: number): { state: GameState; band: InstanceId } {
  let state = gameAtFirstTurn({
    cards: [PHOTON, BAND_CARD, ALLY, DUP],
    deps,
    deck: [PHOTON.id, BAND_CARD.id, DUP.id, ...copiesOf(ALLY.id, 5)],
  });
  for (let i = 0; i < allies; i++) state = playerCardIntoPlay(state, ALLY.id).state;
  const given = giveCard(state, P1, BAND_CARD.id);
  return { state: given.state, band: given.id };
}

describe("§3.38 resources read from the table", () => {
  it("'[wild] for each ally you control (to a maximum of 3)': 0, 2, then capped at 3", () => {
    for (const [allies, wild] of [
      [0, 0],
      [2, 2],
      [5, 3],
    ] as const) {
      const { state, band } = start(allies);
      expect(handCardResources(state, deps, band, P1, null).wild).toBe(wild);
    }
  });

  it("'the printed resource on [a card in play]': that card's printed resources, none with no such card", () => {
    const { state } = start(0);
    const dup = playerCardIntoPlay(state, DUP.id);
    const read = (s: GameState) =>
      generatedResources(s, { kind: "printedResourcesOf", cards: { name: "photon" } }, null, {
        deps,
        sourceId: dup.id,
        playerId: P1,
      });
    expect(read(dup.state).mental).toBe(0);
    const withPhoton = playerCardIntoPlay(dup.state, PHOTON.id).state;
    expect(read(withPhoton).mental).toBe(1);
  });
});
