import {
  alterEgoAction,
  anyOfCards,
  boost,
  cards,
  chooseCards,
  chosen,
  constant,
  countAmong,
  countOf,
  defineAbilities,
  discardEncounterCards,
  each,
  eachPlayer,
  enemyAttack,
  exhaustYourHero,
  forcedInterrupt,
  forEachPlayer,
  handCountOf,
  ifThen,
  modifyAttack,
  moveCards,
  named,
  not,
  on,
  placeThreat,
  query,
  rule,
  self,
  selectCards,
  spendResources,
  sum,
  thatPlayer,
  theMainScheme,
  theVillain,
  varAtLeast,
  varOf,
  whenRevealed,
  you,
  zone,
} from "../../dsl/index.js";

const SUPERNOVA_HELMET = query("upgrade", { name: "Supernova Helmet" });
const WILD_RESOURCE = { anyPrintedResource: ["wild"] } as const;

/**
 * Weight of the World (28021), Nova's obligation, and his nemesis set: "Bring the War!" (28022, side scheme),
 * Warbringer (28023, nemesis minion), War Delivery (28024, treachery), "The War's Been Brought" (28025, treachery,
 * Surge).
 *
 * **Weight of the World**'s "Give to the Sam Alexander player" is data-level (`HeroIdentityCard.obligationCardId`,
 * `packages/content/src/data/nova/cards.ts` 28001a), matching every other obligation in this engine — RRG Appendix
 * II step 10 shuffles it into the encounter deck itself (`packages/engine/src/setup.ts`), and it resolves like any
 * other encounter card once drawn. Its middle line — "While this card is in play, Supernova Helmet cannot ready" —
 * is a plain `constant(rule({ kind: "cannotReady", … }))`, active only while Weight of the World itself is in play
 * (the same "while this card is in play" reading every other `constant` rule in this codebase gets). The card
 * data's own ability id for this line, `28021.weight-of-the-world-constant`, is a real `constant` (unlike Ghost-
 * Spider's own `-constant`-suffixed ability on Worried Father, which is actually a `whenRevealed` — see that
 * module's own docblock; the two obligations' otherwise-identical naming convention hides two different shapes).
 * The Alter-Ego Action ("Exhaust Sam Alexander → remove this obligation from the game") mirrors Worried Father's own
 * action (`sm/ghost-spider/obligation-nemesis.ts`) without the search: there is nothing else to retrieve first.
 *
 * **"Bring the War!"**'s printed text was missing from MarvelCDB's own public API at ingestion time; this
 * card's `text.printed`/`text.current` (`packages/content/src/data/nova/cards.ts`) were transcribed by hand from
 * the card scan (`assets/card-art/bundles/cards/28022.png`) and confirmed word-for-word against it before this
 * ability was written. "A printed [wild] resource" is `TargetQuery.anyPrintedResource` throughout this set — the
 * icon printed in a card's own bottom-left corner, never an ability-generated resource (ruling, January 11, 2026
 * (3): "the discarded card must have a wild resource icon printed in its bottom-left corner … the only time a
 * 'printed resource' can refer to a resource generated by an ability is when paying a cost"). "1 card they control"
 * is read over the union of that player's hand and their own play-area cards (RRG 1.8 "Ownership and Control",
 * p. 31 — deck and discard pile are not "controlled"): `anyOfCards(zone("hand", …), cards(each(query([], { …
 * }))))`, the same two-selector-pool shape Ghost-Spider's Worried Father (this wave's own `sm/ghost-spider/obligation-
 * nemesis.ts`) already uses for a search across several zones at once. `query([], …)` (no `categories`) matches any
 * card category the `controlledBy: thatPlayer` filter can reach through `cardsInPlay` — their identity, allies,
 * upgrades and supports, never a minion or scheme, which never have a player controller. `controlledBy` (not
 * `controller`, a fixed "you"/"other"/"any"/"encounter" enum read off the *ability's own* controller — it doesn't
 * shift per `forEachPlayer` iteration) is the `TargetQuery` field that takes a live `PlayerRef` like `thatPlayer`.
 * Each player chooses their own card to discard (`chooser: thatPlayer`), and `chooseCards`'s own `min: 1` simply
 * finds no candidates and skips a player with none (the Tombstone "if able" precedent, `wave1/gob/running-
 * interference.ts`'s own docblock) — the printed text names no explicit "if able", but a player cannot discard what
 * they do not have.
 * "For each card discarded this way, place 1 threat here" reads the 0-or-1 cards each iteration actually bound
 * (`countAmong(chosen("tossed"), {})`), the same per-iteration `placeThreat` inside `forEachPlayer` Mass Chaos
 * (`wave2/trors/red-skull.ts`) uses for its own "for each … discarded this way" line.
 *
 * **Warbringer**'s Forced Interrupt fires at his own attack's initiation (`on.enemyAttacks("self", { againstYou:
 * true })`, the Proxima Midnight precedent, `wave4/mts/tower-defense.ts`), buffing that specific attack before it
 * resolves via `modifyAttack` rather than a standing ATK modifier — a `modifyStat` ahead of the call would also
 * buff any other activation of his in the same phase (`enemyAttack`'s own docblock). "For each card with a printed
 * [wild] resource in your hand" is `handCountOf(you, WILD_RESOURCE)`; "you" here resolves through `actingPlayerOf`
 * to the attacked player (an encounter card ability carries no controller of its own — the `sinister-assault.ts`
 * "no explicit playerIs needed" precedent), which is exactly the attacked player's hand this text means.
 *
 * **War Delivery**'s "You may spend a [wild] resource. If you do not, …" is `spendResources({ wild: 1 }, "paid",
 * you)` then `ifThen(not(varAtLeast("paid.made")), …)` — Running Interference's own "either spend … or place
 * threat" shape (`wave1/gob/running-interference.ts`), reused here for an optional-payment-with-an-else rather than a
 * binary choice. "The villain and Warbringer each attack you (even if you are in alter-ego form)" is two separate
 * `enemyAttack` calls: `enemyAttack` (unlike `enemyActivation`) always resolves as an attack regardless of the
 * attacked player's form (`apply-effect.ts`'s own `attacksAgainst` check, `effect.kind === "enemyAttack"` is
 * unconditionally true) — the printed parenthetical documents the engine's actual default rather than requesting a
 * new one, so no extra flag is needed. `named("Warbringer")` resolves to nothing if he isn't in play, so that half
 * of the attack silently no-ops (the same forgiving shape In Cold Blood's own "The Lizard attacks you" uses,
 * `sm/ghost-spider/obligation-nemesis.ts`, when its own nemesis minion isn't in play). The `[star]` Boost —
 * "Place 1 threat on the main scheme for each card with a printed [wild] resource in your hand" — is a plain
 * `boost(placeThreat(handCountOf(you, WILD_RESOURCE), theMainScheme))`.
 *
 * **"The War's Been Brought"**'s Surge is data-level (`keywords: [{ name: "surge" }]`), not scripted (every other
 * Surge card in this codebase). Its When Revealed's X — "the total number of printed [wild] resources on cards in
 * your hand, cards under your control, and cards in your discard pile" — sums three independently-measured pools:
 * `handCountOf` for the hand, `countOf` (restricted to `cardsInPlay`, matching "under your control") for the play
 * area, and a bound discard-pile count for the third. There is no live `ValueSpec` for "cards in a zone matching a
 * filter" outside hand/deck (`packages/engine/src/spec.ts`'s `ValueSpec` union carries `handCount`/`deckCount` but
 * no discard-pile sibling) — worked around, not a gap, the same way `selectCards`'s own `<slot>.count` binding
 * (`spec.ts`'s own docblock) is already used to read a bound pool's size elsewhere: `selectCards("discardWild",
 * zone("discard", you, { filter: WILD_RESOURCE }))` binds the matching discard cards, then `varOf(
 * "discardWild.count")` reads how many. Since a card prints at most one resource icon, "the total number of printed
 * wild resources" and "the count of cards with a printed wild resource" are the same number here.
 */
export const NOVA_OBLIGATION_NEMESIS = defineAbilities({
  // Weight of the World — While this card is in play, Supernova Helmet cannot ready.
  "28021.weight-of-the-world-constant": constant(rule({ kind: "cannotReady", target: SUPERNOVA_HELMET })),
  // Weight of the World — Alter-Ego Action: Exhaust Sam Alexander → remove this obligation from the game.
  "28021.weight-of-the-world-action": alterEgoAction(
    { cost: exhaustYourHero },
    moveCards(cards(self), "removedFromGame"),
  ),

  // "Bring the War!" — When Revealed: Each player discards 1 card they control with a printed [wild] resource. For
  // each card discarded this way, place 1 threat here.
  "28022.when-revealed": whenRevealed(
    forEachPlayer(eachPlayer, [
      chooseCards(
        "tossed",
        anyOfCards(
          zone("hand", thatPlayer, { filter: WILD_RESOURCE }),
          cards(each(query([], { controlledBy: thatPlayer, ...WILD_RESOURCE }))),
        ),
        { min: 1, max: 1, chooser: thatPlayer },
      ),
      moveCards(cards(chosen("tossed")), "discard"),
      placeThreat(countAmong(chosen("tossed"), {}), self),
    ]),
  ),

  // Warbringer — [star] Forced Interrupt: When Warbringer attacks you, he gets +1 ATK for that attack for each card
  // with a printed [wild] resource in your hand. That attack gains overkill.
  "28023.warbringer-forced-interrupt": forcedInterrupt(
    on.enemyAttacks("self", { againstYou: true }),
    modifyAttack({ atkBonus: handCountOf(you, WILD_RESOURCE), keywords: ["overkill"] }),
  ),

  // War Delivery — When Revealed: You may spend a [wild] resource. If you do not, the villain and Warbringer each
  // attack you (even if you are in alter-ego form).
  "28024.when-revealed": whenRevealed(
    spendResources({ wild: 1 }, "paid", you),
    ifThen(not(varAtLeast("paid.made")), [
      enemyAttack(theVillain, { against: you }),
      enemyAttack(named("Warbringer"), { against: you }),
    ]),
  ),
  // War Delivery — [star] Boost: Place 1 threat on the main scheme for each card with a printed [wild] resource in
  // your hand.
  "28024.boost": boost(placeThreat(handCountOf(you, WILD_RESOURCE), theMainScheme)),

  // "The War's Been Brought" — Surge (data). When Revealed: Discard X cards from the top of the encounter deck,
  // where X is the total number of printed [wild] resources on cards in your hand, cards under your control, and
  // cards in your discard pile.
  "28025.when-revealed": whenRevealed(
    selectCards("discardWild", zone("discard", you, { filter: WILD_RESOURCE })),
    discardEncounterCards(
      sum(
        handCountOf(you, WILD_RESOURCE),
        countOf({ controller: "you", ...WILD_RESOURCE }),
        varOf("discardWild.count"),
      ),
    ),
  ),
});
