/**
 * Normalized card data, one folder per ingested cycle/pack. Everything under
 * `core/` is generated by `pnpm --filter @mc/content ingest` — edit the
 * curation in `scripts/marvelcdb/curation/` instead, then regenerate.
 */
export type { CardProvenance, DroppedSourceRecord } from "./types.js";
export * from "./core/index.js";
export * from "./pool-version.js";

// ---------------------------------------------------------------------------------------------------------------
// Wave 1 (PLAN.md Phase 7): the Green Goblin and The Wrecking Crew scenario packs, plus the Captain America,
// Ms. Marvel, Thor, Black Widow, Doctor Strange and Hulk hero packs. See docs/phase7-wave1.md.
//
// `@mc/engine`, `coreScenario()` and the client keep using the `CORE_*` exports above until the engine grows the
// primitives docs/phase7-wave1.md §3 lists (several villains at once, double-sided villain/encounter cards, an
// identity's separate deck, ...) — these `WAVE1_*` exports are `@mc/content`-only aggregates for now, not wired
// into anything that runs a game yet.
// ---------------------------------------------------------------------------------------------------------------
export * from "./gob/index.js";
export * from "./twc/index.js";
export * from "./cap/index.js";
export * from "./msm/index.js";
export * from "./thor/index.js";
export * from "./bkw/index.js";
export * from "./drs/index.js";
export * from "./hlk/index.js";

// ---------------------------------------------------------------------------------------------------------------
// Wave 2 (PLAN.md Phase 7, "Wave 2 scope decided (2026-09-18)"): cycle 1. The Rise of Red Skull (`trors`:
// Hawkeye, Spider-Woman and five scenarios), The Once and Future Kang (`toafk`), and the Ant-Man, Wasp,
// Quicksilver and Scarlet Witch hero packs. See docs/phase7-wave2.md and docs/phase7-wave2-data.md.
//
// As with wave 1, `@mc/engine`, `coreScenario()` and the client keep using the `CORE_*` exports until the engine
// grows cycle 1's primitives (docs/phase7-wave2.md §3: separate game areas, three-sided identities, and the
// rest) — these `WAVE2_*` exports are `@mc/content`-only aggregates, not wired into anything that runs a game.
// No `ScenarioCuration` has been written yet for any of the six packs (docs/phase7-wave2-data.md §2), so
// `WAVE2_SCENARIOS` is empty even though wave 2's own scenario data (villains, main schemes, encounter cards) is
// fully present in `WAVE2_CARDS`.
// ---------------------------------------------------------------------------------------------------------------
export * from "./ant/index.js";
export * from "./wsp/index.js";
export * from "./qsv/index.js";
export * from "./scw/index.js";
export * from "./trors/index.js";
export * from "./toafk/index.js";

import type { AnyCard, EncounterSet, Scenario, StarterDeck } from "../schema/index.js";
import { CORE_CARDS } from "./core/cards.js";
import { GOB_CARDS } from "./gob/cards.js";
import { GOB_SCENARIOS } from "./gob/scenarios.js";
import { TWC_CARDS } from "./twc/cards.js";
import { TWC_SCENARIOS } from "./twc/scenarios.js";
import { CAP_CARDS } from "./cap/cards.js";
import { CAP_STARTER_DECKS } from "./cap/starterDecks.js";
import { MSM_CARDS } from "./msm/cards.js";
import { MSM_STARTER_DECKS } from "./msm/starterDecks.js";
import { THOR_CARDS } from "./thor/cards.js";
import { THOR_STARTER_DECKS } from "./thor/starterDecks.js";
import { BKW_CARDS } from "./bkw/cards.js";
import { BKW_STARTER_DECKS } from "./bkw/starterDecks.js";
import { DRS_CARDS } from "./drs/cards.js";
import { DRS_STARTER_DECKS } from "./drs/starterDecks.js";
import { HLK_CARDS } from "./hlk/cards.js";
import { HLK_STARTER_DECKS } from "./hlk/starterDecks.js";
import { GOB_ENCOUNTER_SETS } from "./gob/encounterSets.js";
import { TWC_ENCOUNTER_SETS } from "./twc/encounterSets.js";
import { CAP_ENCOUNTER_SETS } from "./cap/encounterSets.js";
import { MSM_ENCOUNTER_SETS } from "./msm/encounterSets.js";
import { THOR_ENCOUNTER_SETS } from "./thor/encounterSets.js";
import { BKW_ENCOUNTER_SETS } from "./bkw/encounterSets.js";
import { DRS_ENCOUNTER_SETS } from "./drs/encounterSets.js";
import { HLK_ENCOUNTER_SETS } from "./hlk/encounterSets.js";

/** Every card in the wave 1 pool: Core plus the eight wave 1 packs, in pack order. */
export const WAVE1_CARDS: readonly AnyCard[] = [
  ...CORE_CARDS,
  ...GOB_CARDS,
  ...TWC_CARDS,
  ...CAP_CARDS,
  ...MSM_CARDS,
  ...THOR_CARDS,
  ...BKW_CARDS,
  ...DRS_CARDS,
  ...HLK_CARDS,
];

/** Every wave 1 encounter set (Core's three villain sets are not included: Core's own scenarios/decks are unaffected by wave 1). */
export const WAVE1_ENCOUNTER_SETS: readonly EncounterSet[] = [
  ...GOB_ENCOUNTER_SETS,
  ...TWC_ENCOUNTER_SETS,
  ...CAP_ENCOUNTER_SETS,
  ...MSM_ENCOUNTER_SETS,
  ...THOR_ENCOUNTER_SETS,
  ...BKW_ENCOUNTER_SETS,
  ...DRS_ENCOUNTER_SETS,
  ...HLK_ENCOUNTER_SETS,
];

/** Every wave 1 scenario: Risky Business, Mutagen Formula (Green Goblin) and Breakout (The Wrecking Crew). The six hero packs define no scenario of their own. */
export const WAVE1_SCENARIOS: readonly Scenario[] = [...GOB_SCENARIOS, ...TWC_SCENARIOS];

/** Every wave 1 hero-pack starter deck (Captain America, Ms. Marvel, Thor, Black Widow, Doctor Strange, Hulk). The two scenario packs define no starter deck. */
export const WAVE1_STARTER_DECKS: readonly StarterDeck[] = [
  ...CAP_STARTER_DECKS,
  ...MSM_STARTER_DECKS,
  ...THOR_STARTER_DECKS,
  ...BKW_STARTER_DECKS,
  ...DRS_STARTER_DECKS,
  ...HLK_STARTER_DECKS,
];

import { ANT_CARDS } from "./ant/cards.js";
import { ANT_STARTER_DECKS } from "./ant/starterDecks.js";
import { ANT_ENCOUNTER_SETS } from "./ant/encounterSets.js";
import { WSP_CARDS } from "./wsp/cards.js";
import { WSP_STARTER_DECKS } from "./wsp/starterDecks.js";
import { WSP_ENCOUNTER_SETS } from "./wsp/encounterSets.js";
import { QSV_CARDS } from "./qsv/cards.js";
import { QSV_STARTER_DECKS } from "./qsv/starterDecks.js";
import { QSV_ENCOUNTER_SETS } from "./qsv/encounterSets.js";
import { SCW_CARDS } from "./scw/cards.js";
import { SCW_STARTER_DECKS } from "./scw/starterDecks.js";
import { SCW_ENCOUNTER_SETS } from "./scw/encounterSets.js";
import { TRORS_CARDS } from "./trors/cards.js";
import { TRORS_STARTER_DECKS } from "./trors/starterDecks.js";
import { TRORS_ENCOUNTER_SETS } from "./trors/encounterSets.js";
import { TOAFK_CARDS } from "./toafk/cards.js";
import { TOAFK_ENCOUNTER_SETS } from "./toafk/encounterSets.js";

/** Every card in the wave 2 (cycle 1) pool: Core plus the six cycle 1 packs, in release order. */
export const WAVE2_CARDS: readonly AnyCard[] = [
  ...CORE_CARDS,
  ...TRORS_CARDS,
  ...TOAFK_CARDS,
  ...ANT_CARDS,
  ...WSP_CARDS,
  ...QSV_CARDS,
  ...SCW_CARDS,
];

/** Every cycle 1 encounter set (Core's own villain sets are not included, matching `WAVE1_ENCOUNTER_SETS`). */
export const WAVE2_ENCOUNTER_SETS: readonly EncounterSet[] = [
  ...TRORS_ENCOUNTER_SETS,
  ...TOAFK_ENCOUNTER_SETS,
  ...ANT_ENCOUNTER_SETS,
  ...WSP_ENCOUNTER_SETS,
  ...QSV_ENCOUNTER_SETS,
  ...SCW_ENCOUNTER_SETS,
];

/**
 * Every cycle 1 scenario. Empty: no `ScenarioCuration` has been written yet for any of the six packs (the
 * per-scenario setup notes are researched in docs/phase7-wave2.md §2, but turning them into `Scenario` records is
 * a follow-up — see docs/phase7-wave2-data.md). `WAVE2_CARDS` already carries every scenario's villain, main
 * scheme and encounter cards.
 */
export const WAVE2_SCENARIOS: readonly Scenario[] = [];

/**
 * Every cycle 1 starter deck: Hawkeye and Spider-Woman (`trors`), plus one each for Ant-Man, Wasp, Quicksilver
 * and Scarlet Witch. The Once and Future Kang is a scenario pack and defines no starter deck of its own.
 */
export const WAVE2_STARTER_DECKS: readonly StarterDeck[] = [
  ...TRORS_STARTER_DECKS,
  ...ANT_STARTER_DECKS,
  ...WSP_STARTER_DECKS,
  ...QSV_STARTER_DECKS,
  ...SCW_STARTER_DECKS,
];

// ---------------------------------------------------------------------------------------------------------------
// Data-only pool (PLAN.md Phase 7, "All 62 non-Core packs become card data; only wave 1 is scripted"/"Wave 2
// scope decided": every pack beyond Core, wave 1 and cycle 1 is card data the deck builder can show and
// `validateDeck` can judge — NOT playable, because no ability script exists for any of these cards yet
// (`unscriptedCards`, `@mc/engine`, is what actually marks a card unplayable at setup time; this pool is only
// the data half of that). Every pack here normalized with ZERO hand corrections needed (a schema-neutral parser
// fix or a single curated `Correction`/`Errata` was enough — see each pack's own `curation/<code>.ts` for
// specifics) — see docs/phase7-wave2-data.md for the full 56-pack survey this was drawn from and what's left.
// ---------------------------------------------------------------------------------------------------------------
export * from "./bp/index.js";
export * from "./cyclops/index.js";
export * from "./gambit/index.js";
export * from "./drax/index.js";
export * from "./gam/index.js";
export * from "./stld/index.js";
export * from "./vnm/index.js";
export * from "./nebu/index.js";
export * from "./warm/index.js";
export * from "./vision/index.js";
export * from "./ncrawler/index.js";
export * from "./magneto/index.js";
export * from "./winter/index.js";
export * from "./falcon/index.js";
export * from "./ron/index.js";

import { BP_CARDS } from "./bp/cards.js";
import { BP_ENCOUNTER_SETS } from "./bp/encounterSets.js";
import { CYCLOPS_CARDS } from "./cyclops/cards.js";
import { CYCLOPS_ENCOUNTER_SETS } from "./cyclops/encounterSets.js";
import { GAMBIT_CARDS } from "./gambit/cards.js";
import { GAMBIT_ENCOUNTER_SETS } from "./gambit/encounterSets.js";
import { DRAX_CARDS } from "./drax/cards.js";
import { DRAX_ENCOUNTER_SETS } from "./drax/encounterSets.js";
import { GAM_CARDS } from "./gam/cards.js";
import { GAM_ENCOUNTER_SETS } from "./gam/encounterSets.js";
import { STLD_CARDS } from "./stld/cards.js";
import { STLD_ENCOUNTER_SETS } from "./stld/encounterSets.js";
import { VNM_CARDS } from "./vnm/cards.js";
import { VNM_ENCOUNTER_SETS } from "./vnm/encounterSets.js";
import { NEBU_CARDS } from "./nebu/cards.js";
import { NEBU_ENCOUNTER_SETS } from "./nebu/encounterSets.js";
import { WARM_CARDS } from "./warm/cards.js";
import { WARM_ENCOUNTER_SETS } from "./warm/encounterSets.js";
import { VISION_CARDS } from "./vision/cards.js";
import { VISION_ENCOUNTER_SETS } from "./vision/encounterSets.js";
import { NCRAWLER_CARDS } from "./ncrawler/cards.js";
import { NCRAWLER_ENCOUNTER_SETS } from "./ncrawler/encounterSets.js";
import { MAGNETO_CARDS } from "./magneto/cards.js";
import { MAGNETO_ENCOUNTER_SETS } from "./magneto/encounterSets.js";
import { WINTER_CARDS } from "./winter/cards.js";
import { WINTER_ENCOUNTER_SETS } from "./winter/encounterSets.js";
import { FALCON_CARDS } from "./falcon/cards.js";
import { FALCON_ENCOUNTER_SETS } from "./falcon/encounterSets.js";
import { RON_CARDS } from "./ron/cards.js";
import { RON_ENCOUNTER_SETS } from "./ron/encounterSets.js";

/**
 * Every card in the data-only pool: 15 packs across cycles 3, 4, 6, 8, 9 and one non-cycle promotional release,
 * in pack-code alphabetical order (no release-order relationship spans this many cycles at once, unlike
 * `WAVE1_CARDS`/`WAVE2_CARDS`). Not included in `WAVE1_CARDS`/`WAVE2_CARDS`/`CORE_CARDS` — a client that wants
 * "every known card, playable or not" concatenates this with those.
 */
export const DATA_ONLY_CARDS: readonly AnyCard[] = [
  ...BP_CARDS,
  ...CYCLOPS_CARDS,
  ...GAMBIT_CARDS,
  ...DRAX_CARDS,
  ...GAM_CARDS,
  ...STLD_CARDS,
  ...VNM_CARDS,
  ...NEBU_CARDS,
  ...WARM_CARDS,
  ...VISION_CARDS,
  ...NCRAWLER_CARDS,
  ...MAGNETO_CARDS,
  ...WINTER_CARDS,
  ...FALCON_CARDS,
  ...RON_CARDS,
];

/** Every data-only pool encounter set. */
export const DATA_ONLY_ENCOUNTER_SETS: readonly EncounterSet[] = [
  ...BP_ENCOUNTER_SETS,
  ...CYCLOPS_ENCOUNTER_SETS,
  ...GAMBIT_ENCOUNTER_SETS,
  ...DRAX_ENCOUNTER_SETS,
  ...GAM_ENCOUNTER_SETS,
  ...STLD_ENCOUNTER_SETS,
  ...VNM_ENCOUNTER_SETS,
  ...NEBU_ENCOUNTER_SETS,
  ...WARM_ENCOUNTER_SETS,
  ...VISION_ENCOUNTER_SETS,
  ...NCRAWLER_ENCOUNTER_SETS,
  ...MAGNETO_ENCOUNTER_SETS,
  ...WINTER_ENCOUNTER_SETS,
  ...FALCON_ENCOUNTER_SETS,
  ...RON_ENCOUNTER_SETS,
];
