import { trait } from "@mc/content";
import type { TargetQuery } from "@mc/engine";
import {
  addCounters,
  after,
  boostIconsOn,
  chooseTarget,
  chosen,
  constant,
  countOf,
  countersOn,
  dealDamage,
  defineAbilities,
  discardEncounterCards,
  draw,
  eventSource,
  exists,
  gets,
  heal,
  heroResponse,
  ifThen,
  on,
  playOnlyIf,
  query,
  ready,
  refMatches,
  resourcesPaidBy,
  response,
  forcedResponse,
  self,
  varOf,
} from "../../dsl/index.js";

const WEB_WARRIOR = trait("WEB-WARRIOR");
const TECH = trait("TECH");

/**
 * "A Web-Warrior card you control": in this box, the identity's own hero face (31001a SP//dr Suit), Spider-Man
 * Noir (31015), Spider-Ham (31021) and Spider-Man / Otto Octavius (31022) all print the trait
 * (`packages/content/src/data/spdr/cards.ts`) — the `spiderham/allies.ts` `A_WEB_WARRIOR_CARD` precedent's own
 * shape, scoped to this module.
 */
const A_WEB_WARRIOR_CARD: TargetQuery = {
  categories: ["identity", "ally", "upgrade", "support"],
  trait: WEB_WARRIOR,
  controller: "you",
};

/**
 * SP//dr's own five non-signature-identity allies scripted here: VEN#m (31003), Daredevil (31014), Spider-Man Noir
 * (31015, constant only — see below), Spider-Ham (31021), Spider-Man / Otto Octavius (31022). Read directly off
 * `packages/content/src/data/spdr/cards.ts` (no errata on RRG 1.8 pp. 67–68). Every one of these five shares a
 * printed title with a different card elsewhere in the pool (Daredevil the hero, Spider-Man Noir's own villain-deck
 * namesakes, Spider-Ham's own identity, "Spider-Man" printed on several other allies/identities across `sm`) — none
 * of that is aliasing: each is its own physical card with its own id and its own printed text, scripted
 * independently here.
 *
 * **VEN#m (ally, 31003)** — "[star] VEN#m gets +1 THW and +1 ATK for each sym counter on her.\nHero Response: After
 * VEN#m enters play, place 1 sym counter on her for each resource generated by SP//dr Suit's 'Sync Ratio' ability to
 * pay for her." The printed "[star]" is a unique-icon glyph, not a keyword (Lady Spider's own precedent,
 * `spiderham/allies.ts`), scripted as a plain `constant`. The stat bonus is `gets("thw"/"atk", countersOn(self,
 * "sym"), { self: true })` (Drax's own "+1 ATK for each vengeance counter" precedent, `wave3/drax/drax-kit.ts`
 * 19001a). "Hero Response" is `heroResponse` (only fires in hero form; the engine's own `form` gate). "For each
 * resource generated by SP//dr Suit's 'Sync Ratio' ability to pay for her" is `resourcesPaidBy("31001a.sync-ratio")`
 * (§3.16, `identity.ts`'s own docblock names this exact card) — 0 when she was paid for with hand/resource cards
 * alone, whatever Sync Ratio generated toward her payment otherwise (capped by nothing else: "for each resource
 * generated" counts every one, not just the ones needed to cover her printed cost).
 *
 * **Daredevil (ally, 31014)** — "Response: After Daredevil defends against an attack, move 1 damage from him to the
 * attacking enemy." Not printed as "(attack)" (unlike Vibranium Suit's own explicit "Special (attack): Move …",
 * `core/heroes/black-panther.ts` 01049), so this is not an attack: no guard check should gate which enemy the
 * damage can move to (it must always be "the attacking enemy," the one Daredevil just defended against, regardless
 * of whether some other enemy has guard), and no retaliate/"after X attacks" surface should open for a plain
 * damage transfer. That rules out `attack(..., { moveDamageFrom })` (`spec.ts`'s own "'move N damage from your hero
 * to an enemy' (capped by the damage there)" doc is for the attack-labeled shape only) — composed instead from two
 * already-landed effects: `heal(1, self, { bind: "moved" })` reports the amount actually healed (capped at the
 * damage there, RRG 1.8 "Move", p. 30) under `moved.amount` (`core/scenarios/rhino.ts`'s own "Hard to Keep Down"
 * bind precedent), then `dealDamage(varOf("moved.amount"), eventSource)` (not an attack: no guard, no retaliate,
 * `dealDamage`'s own docblock) deals exactly that much to the attacking enemy — `eventSource` on a `defended` event
 * is the attacker (Electrostatic Armor's own precedent, `wave1/hlk/pack-cards.ts` 10031). With no damage on
 * Daredevil (an attack he took no damage from) both effects move/deal 0, a no-op, matching "move 1 damage" having
 * nothing to move.
 *
 * **Spider-Man Noir (ally, 31015)** — "X is equal to the number of facedown cards attached to Spider-Man Noir.
 * \nResponse: After you resolve a treachery, if you control another Web-Warrior card, attach that treachery
 * facedown here (to a maximum of 3)." Only the first sentence (the constant "X" stat) is scripted:
 * `gets("atk"/"thw", countOf({ host: self, facedown: true }), { self: true }, { setBase: true })` (George Stacy's
 * own `{ host: self, facedown: true }` count shape, `sm/ghost-spider/support-upgrades-allies.ts` 27007; `setBase`
 * for a printed "X" stat rather than a bonus atop a numeric base, `core/scenarios/ultron.ts`'s own `FACEDOWN_DRONES`
 * precedent). **Known engine gap, not scripted:** the Response needs "after you resolve a treachery [card]" — a
 * trigger for an encounter card's own resolution finishing (as distinct from its reveal, `on.encounterCardRevealed`
 * / `encounterCardRevealing`, which fires *before* it resolves). No `TriggerEvent` for this exists yet
 * (`packages/engine/src/trigger-events.ts` has no `treacheryResolved`/`encounterCardResolved` kind — only
 * `boostCardResolved`, which is scoped to a boost card during an enemy's activation, not an encounter card revealed
 * in the normal reveal step) and no `EventPattern` wraps it, so there's nothing to attach the response window to
 * without inventing engine state this module doesn't own. The card is legal to play with this gap (data does not
 * require every printed ability to be registered); `31015.spider-man-noir-response` is left off the registry
 * (matching the card's own `abilities` array, which still names it) rather than approximated with a nearby but
 * wrong trigger (attaching on `encounterCardRevealed` would fire before the treachery's own effects, not after).
 *
 * **Spider-Ham (ally, 31021)** — "Play only if you control a Web-Warrior card.\n[star] Forced Response: After
 * Spider-Ham attacks or thwarts, discard the top card of the encounter deck. For each boost icon ([boost])
 * discarded this way, deal 1 damage to Spider-Ham." `playOnlyIf(exists(A_WEB_WARRIOR_CARD))` and
 * `discardEncounterCards(1, { bind: "discarded" })` + `dealDamage(boostIconsOn(chosen("discarded")), self)` are the
 * `spiderham/allies.ts` Scarlet Spider / `sm/ghost-spider` Spider-Man (Hobie Brown) precedents verbatim
 * (`boostIconsOn(chosen(...))` sums every discarded card's boost icons as the damage total, one per icon).
 *
 * **Spider-Man / Otto Octavius (ally, 31022)** — "Play only if you control a Web-Warrior card.\nResponse: After you
 * play Spider-Man from your hand, ready an upgrade you control. If that upgrade has the Tech trait, draw 1 card."
 * `on.youPlayThis()` is "after you play [this card]" (its own docblock). "An upgrade you control" is
 * `chooseTarget("upgrade", query("upgrade", { controller: "you" }))`; with none in play nothing is asked
 * (`chooseTarget`'s own "with no legal target nothing is asked either way" doc) and the `ready`/`ifThen` that follow
 * are no-ops over an empty ref. "If that upgrade has the Tech trait" reads the chosen upgrade itself:
 * `refMatches(chosen("upgrade"), query("upgrade", { trait: TECH }))` (Scarlet Spider's own `refMatches` precedent;
 * no `anywhere: true` needed since the upgrade stays in play throughout).
 */
export const SPDR_ALLIES = defineAbilities({
  "31003.ven-m-constant": constant(
    gets("thw", countersOn(self, "sym"), { self: true }),
    gets("atk", countersOn(self, "sym"), { self: true }),
  ),
  "31003.ven-m-response": heroResponse(
    after.entersPlay("self"),
    addCounters("sym", resourcesPaidBy("31001a.sync-ratio"), self),
  ),

  "31014.daredevil-response": response(
    after.defends(query("ally", { self: true })),
    heal(1, self, { bind: "moved" }),
    dealDamage(varOf("moved.amount"), eventSource),
  ),

  "31015.spider-man-noir-constant": constant(
    gets("atk", countOf({ host: self, facedown: true }), { self: true }, { setBase: true }),
    gets("thw", countOf({ host: self, facedown: true }), { self: true }, { setBase: true }),
  ),

  "31021.spider-ham-constant": constant(playOnlyIf(exists(A_WEB_WARRIOR_CARD))),
  "31021.spider-ham-forced-response": forcedResponse(
    on.attacksOrThwarts("self"),
    discardEncounterCards(1, { bind: "discarded" }),
    dealDamage(boostIconsOn(chosen("discarded")), self),
  ),

  "31022.spider-man-constant": constant(playOnlyIf(exists(A_WEB_WARRIOR_CARD))),
  "31022.spider-man-response": response(
    on.youPlayThis(),
    chooseTarget("upgrade", query("upgrade", { controller: "you" })),
    ready(chosen("upgrade")),
    ifThen(refMatches(chosen("upgrade"), query("upgrade", { trait: TECH })), draw(1)),
  ),
});
