import { trait } from "@mc/content";
import {
  cards,
  chooseCards,
  chooseOne,
  chosen,
  damageAnEnemy,
  defineAbilities,
  discardCardsCost,
  each,
  heroAction,
  ifThen,
  modifyStat,
  moveCards,
  option,
  paidUsingResourceFrom,
  printedCostOf,
  query,
  ready,
  removeThreatFromAScheme,
  shuffleDeck,
  stun,
  you,
  yourIdentity,
  zone,
} from "../../dsl/index.js";

const INTERFACE = trait("INTERFACE");
const TECH = trait("TECH");
const SYNC_RATIO = "31001a.sync-ratio";

/**
 * SP//dr's own events (`spdr` 31004-31006, 31016-31017, 31023; SP//dr Hero Pack pp. 1, 3, 5; read directly off
 * `packages/content/src/data/spdr/cards.ts`, no errata on RRG 1.8 pp. 67-68). All six print printed hero-specific
 * ids/aspects rather than "SP//dr"/"your hero" by name, so every effect sources off `yourIdentity`/`you`
 * (`spiderham/events.ts`'s own reasoning).
 *
 * **All Systems Go! (31004)**: "Hero Action: Choose: • Ready each Interface upgrade you control. • Search your
 * deck and discard pile for an Interface upgrade and add it to your hand. (Shuffle.)" `chooseOne` between
 * `ready(each(query("upgrade", { trait: INTERFACE, controller: "you" })))` and Doctor Strange's own "search …
 * and add … to hand. Shuffle." shape (`chooseCards`/`moveCards`/`shuffleDeck`, `wave1/drs/kit.ts`'s
 * `09006.mystical-studies-action`). **The printed card data (`packages/content/src/data/spdr/cards.ts`) lists
 * three ability refs for this one Hero Action** (`31004.all-systems-go-action`, `-constant`, `-constant-2`) — the
 * card scan (`assets/card-art/bundles/cards/31004.png`) shows only the one Hero Action transcribed above, with no
 * persistent/constant clause. `-constant`/`-constant-2` look like leftover scaffolding (no printed text supports
 * either), not scripted here; flagged for `card-data-pipeline` to confirm/regenerate rather than guessed at.
 *
 * **Rapid Deployment (31005)**: "Hero Action (thwart): Remove 3 threat from a scheme. If you paid for this card
 * using a resource generated by SP//dr Suit's 'Sync Ratio' ability, remove 3 threat from a scheme." The "(thwart)"
 * label only categorizes the triggered ability itself (`spiderham/events.ts`'s own "(attack)"/"(thwart)"
 * reasoning for Swinging Web Pig/Ham It Up) — the printed effect is a flat "remove … threat", not a basic thwart,
 * so `removeThreatFromAScheme`, not `thwart`. Two independent scheme choices (the text says "a scheme" both
 * times, never "that scheme"), the second gated on `paidUsingResourceFrom("31001a.sync-ratio")` — the exact
 * predicate `identity.ts`'s own Sync Ratio docblock and `dsl/values.ts`'s own docblock cite this card by name for.
 *
 * **Web-Trap (31006)**: "Hero Action (attack): Deal 5 damage to an enemy. If you paid for this card using a
 * resource generated by SP//dr Suit's 'Sync Ratio' ability, stun that enemy." Same "(attack)" label reasoning as
 * Spider-Ham's own Swinging Web Pig (`damageAnEnemy`, not an actual attack) — `damageAnEnemy(5)`, then
 * `paidUsingResourceFrom(SYNC_RATIO)` gates `stun(chosen("enemy"))` on the same chosen enemy.
 *
 * **Repurpose (31016)**: `protection` aspect, generic (not `hero:31001a`-scoped) — usable by any hero. "Hero
 * Action: Discard a Tech upgrade you control → ready your hero and choose THW, ATK, or DEF. Until the end of the
 * round, your hero gets +X to the chosen power, where X is equal to that upgrade's printed cost."
 * `discardCardsCost`'s own docblock (`dsl/abilities.ts`) names this exact card for its "Discard a [Tech] upgrade
 * you control →" shape, binding the discarded card to slot `"discarded"`. "Ready your hero" is unconditional,
 * ahead of the choice; each option is `modifyStat(<stat>, printedCostOf(chosen("discarded")), yourIdentity,
 * "endOfRound")` — the QSV Speed Cyclone kit's own "gets +N [stat] … until the end of the round" shape
 * (`wave2/qsv/kit.ts`'s Maximum Velocity, `14005.maximum-velocity-action`), with the amount read off the
 * discarded card's printed cost (`printedCostOf`, Headbutt/Thoughtcasting's own precedent) instead of a constant.
 *
 * **Thwip Thwip! (31017)** — **KNOWN_SKIPPED, two missing primitives, not scripted.** `protection` aspect,
 * generic. "Hero Action: Deal 1 damage to a Web-Warrior character you control → place a total of 2 stun status
 * cards on up to 2 enemies." (Silk's own reprint sibling, "Quick Quip", `silk` 52034, prints the identical cost
 * shape with confused instead of stunned — not scripted either, same gap.)
 * 1. **The cost has no DSL/engine shape.** `AbilityCost` (`packages/engine/src/abilities.ts`) only offers
 *    `damageSelf` (the controller's identity) and `damageThisCard` (the ability's own card) for a "Deal N damage
 *    to X →" cost — nothing for "deal N damage to a *chosen* character matching a query", the shape this card
 *    needs (any Web-Warrior character the player controls, not fixed to one card). Would need a new
 *    `AbilityCost.damageCards` shape mirroring `discardCards`/`exhaustCards`' own `InPlayCostPick` (pick a
 *    candidate from a query, payable only while it can take the damage), which is a `game-rules-architect`-scale
 *    engine change, not something to approximate with an effect-side `dealDamage` ahead of the granted effects (a
 *    cost that cannot be paid must refuse the whole ability at initiation — RRG 1.8 "Cost", p. 13 — which an
 *    effect-side damage step does not enforce).
 * 2. **The effect has no DSL/engine shape either.** `divide` (`dsl/effects.ts`) only distributes `"damage"` or
 *    `"threat"` among a query of targets; there is no equivalent for distributing a total number of *status
 *    cards* (here, 2 stun cards) among up to N chosen targets. `giveStatus`/`stun` place exactly one status per
 *    named target, which cannot express "the chooser may put both on the same enemy or split them across two".
 *
 * **Limitless Stamina (31023)** — `basic` aspect, generic. "Play only if your identity has at least 14 printed hit
 * points.\nHero Action: Ready your hero." The Hero Action is `ready(yourIdentity)`
 * (`31023.limitless-stamina-action`), registered and tested below. **The play restriction
 * (`31023.limitless-stamina-constant`) is KNOWN_SKIPPED — no `ValueSpec` reads a card's printed hit points.**
 * `dsl/abilities.ts`'s own `playOnlyIf`/`constant` builders exist for exactly this "Play only if …" shape
 * (`docs/phase7-wave3.md §3.42`'s own precedent, e.g. `playOnlyIf(valueAtLeast(victoryDisplayCount(...), 1))`),
 * but `ValueSpec` (`packages/engine/src/spec.ts`) has no kind reading a card's own printed HP the way
 * `printedCost`/`totalPrintedResources` read printed cost/resources — the closest existing thing,
 * `AttachmentHost.measure: "printedHp"`, lives in a different type entirely (superlative attachment targeting,
 * `packages/engine/src/query.ts`/`reveal.ts`), not a `ValueSpec` a `compare`/`valueAtLeast` predicate can read. A
 * second card needs the identical primitive for a different shape — "heal damage from your hero equal to that
 * ally's printed hit points" (Noble Sacrifice, `magneto` 49018, not yet scripted) reads a *chosen* card's printed
 * HP as an amount, not just the controller's own identity — so a `ValueSpec { kind: "printedHp"; of: TargetRef }`
 * mirroring `printedCost`'s own shape (`packages/engine/src/actions.ts`/`select.ts`'s `case "printedCost"`) would
 * serve both at once.
 */

export const SPDR_EVENTS = defineAbilities({
  "31004.all-systems-go-action": heroAction(
    chooseOne(
      option(
        "Ready each Interface upgrade you control",
        ready(each(query("upgrade", { trait: INTERFACE, controller: "you" }))),
      ),
      option(
        "Search your deck and discard pile for an Interface upgrade and add it to your hand",
        chooseCards("found", zone(["deck", "discard"], you, { filter: query("upgrade", { trait: INTERFACE }) }), {
          min: 1,
          max: 1,
        }),
        moveCards(cards(chosen("found")), "hand"),
        shuffleDeck(),
      ),
    ),
  ),

  "31005.rapid-deployment-action": heroAction(
    { label: "thwart" },
    ...removeThreatFromAScheme(3, "scheme"),
    ifThen(paidUsingResourceFrom(SYNC_RATIO), removeThreatFromAScheme(3, "scheme2")),
  ),

  "31006.web-trap-action": heroAction(
    { label: "attack" },
    ...damageAnEnemy(5),
    ifThen(paidUsingResourceFrom(SYNC_RATIO), stun(chosen("enemy"))),
  ),

  "31016.repurpose-action": heroAction(
    { cost: discardCardsCost(query("upgrade", { trait: TECH, controller: "you" })) },
    ready(yourIdentity),
    chooseOne(
      option("THW", modifyStat("thw", printedCostOf(chosen("discarded")), yourIdentity, "endOfRound")),
      option("ATK", modifyStat("atk", printedCostOf(chosen("discarded")), yourIdentity, "endOfRound")),
      option("DEF", modifyStat("def", printedCostOf(chosen("discarded")), yourIdentity, "endOfRound")),
    ),
  ),

  // 31017.thwip-thwip-action — KNOWN_SKIPPED, see module docblock (missing AbilityCost.damageCards and a
  // status-card sibling of `divide`).

  "31023.limitless-stamina-action": heroAction(ready(yourIdentity)),
  // 31023.limitless-stamina-constant — KNOWN_SKIPPED, see module docblock (missing ValueSpec { kind: "printedHp" }).
});
